### ISSUE TITLE
I can't create fetch artifact task in jobs

### ISSUE THREAD

**Issue by zszen** [gocd/docker-registry-artifact-plugin#1037]
"The plugin with which the artifact is associated cannot be determined because: the pipeline, stage, job or artifact id is a parameter or is non-existent. Please choose a plugin to configure the plugin properties."

![img](https://github.com/gocd/docker-registry-artifact-plugin/assets/1890538/d3e0ea6a-c72b-4828-a8b3-e2c1d22d4215)

**Comment by chadlwilson** [comment]
Please describe your problem more clearly and why you think you have your pipelines configured correctly, or what you have done to try and solve the problem.

Your pipeline would need to have an earlier stage or an upstream pipeline that is publishing the artifact with ID `docker-33.251` in the artifact configuration. Have you configured that correctly?

**Comment by zszen** [comment]
gocd-server version : v23.5.0
linux centos 7 env.
artifact id docker-33.251

![](https://github.com/gocd/docker-registry-artifact-plugin/assets/1890538/ad199b3b-e519-439c-8087-f14ea6f2f957)


I want put it to the commands beginning after added it.

![](https://github.com/gocd/docker-registry-artifact-plugin/assets/1890538/29af9848-db81-40b3-9b5d-f39d6f4f462f)

**Comment by zszen** [comment]
"Specify the pipeline, stage and job name."

I don't know how to fill it.

![](https://github.com/gocd/docker-registry-artifact-plugin/assets/1890538/ccb57850-69ab-4ac9-86a1-7a4770815754)

![](https://github.com/gocd/docker-registry-artifact-plugin/assets/1890538/f011dbc8-764d-4b5f-a89d-7758a287022b)

![](https://github.com/gocd/docker-registry-artifact-plugin/assets/1890538/019fc201-7194-4001-acda-3d99cd889ba1)

![](https://github.com/gocd/docker-registry-artifact-plugin/assets/1890538/51a9af5a-2597-4419-aff5-517c4c28a5bf)

**Comment by zszen** [comment]
Now I can create fecth artifact. But the pipeline dont work well. And I don't know why the docker artifact need a before job.

```
format_version: 10
pipelines:
  pp-docker-build-test:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-29a3d2a:
        git: http://10.0.68.37/platform/deployment/zszen/cicd-test-docker
        username: zhaoshouzheng
        shallow_clone: true
        auto_update: true
        branch: master
        encrypted_password: AES:shWgS/69PctRLTEabOLtiA==:01Pbrhr8jOquuL/2l/yAlQ==
    stages:
    - test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          test:
            timeout: 0
            tasks:
            - exec:
                command: ls
                run_if: passed
    - st-docker-build-test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          jb-docker-build-test:
            timeout: 0
            resources:
            - network
            tasks:
            - exec:
                arguments:
                - deal.sh
                command: sh
                run_if: passed
            - fetch:
                is_file: false
                source: docker
                destination: ''
                stage: test
                job: test
                artifact_origin: gocd
                run_if: passed
```
